### ISSUE TITLE
Saving user information

### ISSUE THREAD

**Issue by luketd** [Simulation-Hockey-League/discord-bot#1]
Command structure
/store [username]

Purpose: Links the discord information of the user with the portalid of the user. Able to link username to active player in order to retrieve information

Options: None

Error Response: if portalid is not found

Questions: 
     How do we want to store the information. Would we want to user sqlite and host it there, or use phpMyAdmin
     How do we want to handle storing additional information. Team, Username, etc. Do we want to store it in a db. Or access it through the api each time. through the API would be the best way

**Comment by esilverm** [comment]
Completed in #13

**Comment by esilverm** [comment]
Completed in #13
